import { useState, useEffect } from 'react'
import { runtime, tabs } from 'webextension-polyfill';

import './Popup.css'

export const Popup = () => {
  console.log("=== Popup rendered");
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    console.log("--- useEffect Popup")
    // chrome.storage.sync.get(['count'], (result) => {
    //   setCount(result.count || 0)
    // })
  }, [])

  useEffect(() => {
    console.log("--- useEffect,count Popup")
    // chrome.storage.sync.set({ count })
    runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main>
      <h1><a href="options.html" target="_blank">OptionsPage</a></h1>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
